# Generated by Django 4.1.5 on 2023-02-02 03:49

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=storeapp.models.get_file_path
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("discription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=storeapp.models.get_file_path
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("tittle", models.CharField(max_length=150)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
