# Generated by Django 4.1.5 on 2023-02-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="status",
            new_name="des",
        ),
    ]
