# Generated by Django 4.1.5 on 2023-02-03 12:53

from django.db import migrations, models
import storeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0002_rename_status_teacher_des"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fac_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=storeapp.models.get_file_path
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("desc", models.TextField()),
            ],
        ),
    ]
